<!-- jQuery
	***must be before bootstrap otherwise data-toggle doesn't work
-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	
	
<!-- Bootstrap -->

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
		integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

		
<!-- Bootstrap Select Plug-in: http://silviomoreto.github.io/bootstrap-select/ -->
		
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/js/bootstrap-select.min.js"></script>




<!-- jQuery datepicker -->

	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	
	<!-- <script src="/PhalconCV/public/js/datepicker.js" ></script> -->
	{{ javascript_include( 'public/css/style404.css' ) }}