
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


<!-- CSS Bootstrap -->

	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" 
		integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

			
<!-- Bootstrap Select Plug-in: http://silviomoreto.github.io/bootstrap-select/ -->

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/css/bootstrap-select.min.css">


<!-- Custom local CSS -->

	<!-- <link href="/PhalconCV/public/css/style.css" rel="stylesheet"> -->
	{{ stylesheet_link("public/css/style.css") }}

<!-- jQuery datepicker CSS -->

	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	

